kind: Deployment
apiVersion: apps/v1
metadata:
  name: loghme-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loghme-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loghme-frontend
    spec:
      containers:
        - name: loghme-frontend
          image: aminhoseinorg/loghme-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 0.2
              memory: 200Mi
            # requests:
            #   cpu: 185m
            #   memory: 185Mi
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: loghme-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31085
  selector:
    app: loghme-frontend